### ISSUE TITLE
keystatic.config.ts not found

### ISSUE THREAD

**Issue by geroxima** [Thinkmill/keystatic#1030]
Framework: Astro

Description:
I'm currently developing an educational platform using Keystatic within the Astro framework. As part of this development, I've integrated a LaTeX notation component into the editor, allowing our writers to seamlessly insert LaTeX into their posts. 

Editor View:
![Editor View](https://github.com/Thinkmill/keystatic/assets/62658933/cda96a36-fa99-4223-97a9-c9dd21710997)

Rendered Result:
![Rendered Result](https://github.com/Thinkmill/keystatic/assets/62658933/c2cdbd73-0cb5-4bc1-9bef-0b7d22ff08e1)

I'm aiming to render LaTeX styles within the editor itself. I've attempted to achieve this by following the steps outlined in the [Add Component Blocks To The Document Field In Keystatic](https://youtu.be/azGgZf2jW_o?si=yip4DCFGY9RTM1BG) video tutorial. However, when I change the `keystatic.config.ts` file to `.tsx`, the Keystatic Admin UI fails to display, and I encounter the following error: `[404] /keystatic.config.ts`.

Error Screenshot:
![Error Screenshot](https://github.com/Thinkmill/keystatic/assets/62658933/3c776322-a111-4133-a6f8-4777f6b5edef)

I'm specifically trying to render two Content Components, one for inline LaTeX and another for block LaTeX. These components are implemented as Astro components. Do I necessarily require a React component to render in the Admin UI? how can I resolve the `404 error` within Astro?

Link to the repository I'm working with: [Ideal Project Repository](https://github.com/IdealProject/ideal)

Any assistance or guidance on resolving this issue would be greatly appreciated. Thank you!

**Comment by simonswiss** [comment]
Hey!

Unfortunately, you need React components to display something inside the Keystatic Admin UI, since Keystatic is a React app.

I know it's sort of frustrating, but you have to double up your effort at the moment to re-create the same components for preview in the Admin UI.

As per the `.tsx` config extension — when you change the config file from `.ts` to `.tsx` you need to restart the server manually, and sometimes also delete the generated `.astro` folder. The config file will eventually start working again.

**Comment by geroxima** [comment]
Thank you so much for responding, after sometime I've realized about the `.astro` folder being the problem. I did add eventually a react component for the latex notation, but it was later remove because some optimization problems.
