### ISSUE TITLE
mdx field does not correctly save bold links

### ISSUE THREAD

**Issue by stefanprobst** [Thinkmill/keystatic#1135]
repro: https://github.com/stefanprobst/issue-keystatic-bold-link

i have a .mdx file, which was not created via keystatic, with the following content:

```mdx
This paragraph has **some bold text with [a link](http://example.com)**.
```

this displays correctly in next.js, and also when initially loaded in keystatic:

next.js:
![01](https://github.com/Thinkmill/keystatic/assets/20753323/6a598001-35cd-4eb5-b9f3-18e638ae3712)

keystatic:

![02](https://github.com/Thinkmill/keystatic/assets/20753323/706d2e11-e67a-4646-a839-b22b04ad632c)

however, when adding more text via keystatic and pressing "Save", the file is saved incorrectly:

```mdx
This paragraph has **some bold text with **[**a link**](http://example.com).

Add some more text.
``` 

which displays as:

next.js:

![04](https://github.com/Thinkmill/keystatic/assets/20753323/8e155d1b-5b1c-4de8-99a4-b3755db189b5)

keystatic:

![03](https://github.com/Thinkmill/keystatic/assets/20753323/d1783829-2ba4-4ac3-a138-750d4e2d9c5e)

**Comment by tordans** [comment]
@emmatown I am running `"@keystatic/core": "^0.5.26"` in Astro and I am still seeing this issue. Your fix should be [released since 0.5.17](https://github.com/Thinkmill/keystatic/blob/main/packages/keystatic/CHANGELOG.md#0517), right?

Could the be still there or re-appeared?

> <img width="837" alt="image" src="https://github.com/Thinkmill/keystatic/assets/111561/34f4d587-2d1b-4687-88e0-9a61e9195d6e">

In this case, I select link + text after link and use cmd+b to make it bold.
