### ISSUE TITLE
Image compatibility with `astro:assets`

### ISSUE THREAD

**Issue by simonswiss** [Thinkmill/keystatic#471]
Astro's [`assets` functionality](https://docs.astro.build/en/guides/assets/#overview) (experimental but about to drop in stable) is able to import images from content collection (markdoc files in Keystatic's case) using *relative* paths:

https://docs.astro.build/en/guides/assets/#update-content-collections-schemas

It's _almost_ possible to make it work with Keystatic images by setting the `directory` to `src/assets/...` and then the `publicPath` referencing the correct folder (`src/assets/...` or `../../assets/...`).

But right now, Keystatic prepends a `/` in front of the `publicPath`, which makes it impossible to have Astro's assets working with Keystatic images.

More context can be found in #330 and #372.

I have myself been struggling with this on the "Built with Keystatic" project — and haven't found any solution that works, including doing dynamic imports with Vite.

All it would need to work, I _think_, is the ability to strip the `/` from the `publicPath`.

**Comment by JedWatson** [comment]
As of `@keystatic/core@0.0.112` we're no longer prepending the / at the start of publicPath for images.

Heads up this _may_ be a breaking change for anyone depending on the / prefix without specifying it; the fix for those cases would be to explicitly specify it when you need it. 

Because Keystatic functionally can't lose any data, and this can't be tested for, we decided to ship it in the interest of unblocking compatibility with `astro:assets`, hopefully this is the right step!
