### ISSUE TITLE
Create empty state for collections without items

### ISSUE THREAD

**Issue by teinett** [Thinkmill/keystatic#507]
I started new project Astro + Keystatic, using official docs https://keystatic.com/docs/installation-astro.

I setup my first collection "posts" and opened Keystatic admin:

<img width="1068" alt="keystatic-astro-empty-state" src="https://github.com/Thinkmill/keystatic/assets/1038168/3903221f-c234-415e-bc11-43103b655cbf">

**I got error**: 
```
Unable to load collection
JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

**Expected to see**: empty state of this list, not an error.

**Comment by simonswiss** [comment]
This typically happens when you don't have [the Keystatic API route](https://keystatic.com/docs/installation-astro#keystatic-api-routes) set up properly.

There is an empty collection UI, it looks like this:

<img width="1255" alt="CleanShot 2023-08-09 at 13 15 05@2x" src="https://github.com/Thinkmill/keystatic/assets/485747/115c3304-bb10-4525-b02d-5d8ed3047226">

**Comment by teinett** [comment]
I hope to see this empty static after closing https://github.com/Thinkmill/keystatic/issues/508 😄

**Comment by JedWatson** [comment]
Closing this as #508 has also been closed, and the fix has been added to our astro template which will hopefully reduce others also hitting this issue in the future.
