### ISSUE TITLE
Error: Invalid directory in content serialization | Document Field Image configuration directory & publicPath

### ISSUE THREAD

**Issue by NeeshSamsi** [Thinkmill/keystatic#578]
At the end of #520, @simonswiss added a sidenote saying that instead of `images: true`, I could pass in a configuration object with the directory & publicPath fields. So I decided to use this to save the images into the public directory so I can access it within my Next.js app.

```tsx
// keystatic.config.tsx
    // fields.document ... ({
          images: {
            directory: "public/images/blogposts/",
            publicPath: "/images/blogposts/",
            schema: {
              alt: fields.text({
                label: "Image Alternate Text",
                description:
                  "This is read out to visually impaired users and displayed in a situation where the image was unable to load for any reason.",
                validation: {
                  length: { min: 1 },
                },
              }),
              title: fields.text({
                label: "Image Caption",
                description: "This is optional. Displayed under the image.",
              }),
            },
          },
```
[Link to repo](https://github.com/inquisitblog/inquisit/tree/add-keystatic)

While editing the Document Field in the Blog Posts Collection, clicking on adding an image, opens up the File Explorer dialog. Choosing an image causes this error
![image](https://github.com/Thinkmill/keystatic/assets/72866286/c70d1f02-dc71-47cd-86fc-d82089db6261)

**Comment by JedWatson** [comment]
Hey @NeeshSamsi 

I check out your repo and can reproduce the error.

The problem is your directory config has a trailing slash:

```
directory: "public/images/blogposts/"
```

If you remove the last `/` then it works as expected.

I do think this is a bug, in that you shouldn't be able to break it with a trailing slash, or at least we should warn you or have a better error, but for now you can update the config and get past the problem, I'll leave this issue open until we fix the config / error message!
