### ISSUE TITLE
Bug: nested component blocks

### ISSUE THREAD

**Issue by florian-lefebvre** [Thinkmill/keystatic#594]
I have a custom `button` component block that needs to be in a table cell. In the markdoc file, it works fine
```md
{% table %}
- Platform
- Type
- Price
- Link
---
- Legis Music
- One-time payment
- From $49/lifetime
- {% button text="Here" href="/licenses" /%}
{% /table %}
```

But in keystatic, it doesn't show in the cell and can't be done at all
![image](https://github.com/Thinkmill/keystatic/assets/69633530/3ac4e28e-5b1b-4d3e-97b2-98cb8f92cc3e)

**Comment by JedWatson** [comment]
@emmatown may be able to comment on this with more details

I know that, currently, nested component blocks aren't possible, and that limitation is something we're working to resolve with the new `Markdoc` field we're building (which switches out Slate for Prosemirror, long story) but also that's a little while off because there's a lot to do to really achieve our vision for how it should work.

Having said that, I thought we had support for using custom component blocks inside the tags that we have built-in support for (specifically they do work inside layout tags) so having them work inside of tables _should_ be possible, and we can look into it.

**Comment by florian-lefebvre** [comment]
Definitely interested in nesting blocks inside markdoc nodes. Nesting blocks into blocks is not a blocker for me rn

**Comment by JedWatson** [comment]
It looks like we should be able to do something about this, will get back to you soon to confirm

**Comment by florian-lefebvre** [comment]
@JedWatson can i help in any way?

**Comment by JedWatson** [comment]
@florian-lefebvre we haven't had a chance to try it yet, but _in theory_ we'd need to change the allowed `tableCellChildren` here to allow `component-block` nodes here: https://github.com/Thinkmill/keystatic/blob/6b9c653c33e8ea491f63d404464a42d7626db91f/packages/keystatic/DocumentEditor/editor.tsx#L99

It may cause some other side effects (the editor is tricky) but if you want to take a look and see how it goes for you, let us know!

**Comment by florian-lefebvre** [comment]
Thanks for pointing me to the right part of the codebase! I'll see if I can do anything

**Comment by emmatown** [comment]
This was one of the things solved with the new editor in `fields.markdoc`/`fields.mdx`.
<img width="1088" alt="a rich text editor with a table and a element named aside inside a cell" src="https://github.com/user-attachments/assets/a2a169d1-d9a3-48df-9aba-50a407a9e14a">
