### ISSUE TITLE
Enhancement: add visual grouping for fields

### ISSUE THREAD

**Issue by m-kulczewski** [Thinkmill/keystatic#641]
With a lot of fields in a singleton, the view becomes cluttered and confusing, visual grouping would help a lot, possibly with optional collapsible, here a rough idea:

<img width="1312" alt="Screenshot 2023-09-15 at 09 19 23" src="https://github.com/Thinkmill/keystatic/assets/16463381/e4af48b1-8aeb-4fc1-a92e-7d4b573bb8ee">

**Comment by jossmac** [comment]
I think you can achieve this with the `object` field, though it's not currently documented 😬 

```js
singleton({
  label: 'General / Settings',
  schema: {
    ...
    someArea: fields.object(
      {
        logo: fields.image({ label: 'Bild oben rechts/JG Logo' }),
        logoLabel: fields.text({ label: 'Logo label' })
      },
      { label: 'Some Area' }
    )
  }
})
```

The important part is the second argument to `fields.object()`, which accepts options:

```ts
type ObjectFieldOptions = {
  label: string;
  description?: string;
};
```

While this doesn't render a `fieldset/legend` (because of some [restrictions around  markup + a11y](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend#technical_summary)), the container is assigned the role of `group` and properly attributed with `aria-labelledby` and `aria-describedby` to remain accessible.

**Comment by jossmac** [comment]
Just tried this out to confirm everything works as expected. It lacks the prominent delineation of your example, which I'd like to revisit in the future. From memory we were concerned about introducing too much chrome, considering that objects may be infinitely nested.

<img width="916" alt="object field options example screen shot" src="https://github.com/Thinkmill/keystatic/assets/2730833/b9117f67-abbc-46c9-ae46-70540a8c7057">
