### ISSUE TITLE
frontmatter not found

### ISSUE THREAD

**Issue by ArnavK-09** [Thinkmill/keystatic#837]
![Screenshot_2023-12-31-00-52-43-44_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/Thinkmill/keystatic/assets/69188140/c4b3c8b3-e2c2-474e-9cc6-59244c5581c4)

**Comment by simonswiss** [comment]
Hey!

Do you have some code to share? Ideally a link to the repo where the issue is happening, with steps to reproduce.

**Comment by ArnavK-09** [comment]
> Hey!
> 
> Do you have some code to share? Ideally a link to the repo where the issue is happening, with steps to reproduce.
@simonswiss 

##### it was working fine before But when I recently tried to Explore data, this error pops out. I haven't changed any code as it was working fine earlier

REPO - https://github.com/ArnavK-09/AvatarArchives

**Comment by simonswiss** [comment]
I cannot log in your Keystatic Cloud account, but I changed the `storage` to `local` and I can see the content just fine:

![CleanShot 2024-01-23 at 10 29 05@2x](https://github.com/Thinkmill/keystatic/assets/485747/03bf1b36-e6fb-4fc8-8f70-05b65b9399ee)

Are you able to see the same page if you change the storage to `local`?

Looks like the [frontmatter for that post is present on GitHub](https://github.com/ArnavK-09/AvatarArchives/blob/main/src/content/avatars/heartiest-adorable-pikachu/index.mdoc) too, so that _should_ work. Which is why I want to check if the problem is isolated to Cloud mode.

Also, try install the latest versions of Keystatic `core` and `astro` and see if it helps.

**Comment by ArnavK-09** [comment]
> I cannot log in your Keystatic Cloud account, but I changed the `storage` to `local` and I can see the content just fine:
> 
> ![CleanShot 2024-01-23 at 10 29 05@2x](https://github.com/Thinkmill/keystatic/assets/485747/03bf1b36-e6fb-4fc8-8f70-05b65b9399ee)
> 
> Are you able to see the same page if you change the storage to `local`?
> 
> Looks like the [frontmatter for that post is present on GitHub](https://github.com/ArnavK-09/AvatarArchives/blob/main/src/content/avatars/heartiest-adorable-pikachu/index.mdoc) too, so that _should_ work. Which is why I want to check if the problem is isolated to Cloud mode.
> 
> Also, try install the latest versions of Keystatic `core` and `astro` and see if it helps.

# it shows no data on storage local

![Screenshot_2024-01-23-19-51-31-99_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/Thinkmill/keystatic/assets/69188140/c98393aa-2791-46f3-8a91-5479f93020c0)

Ps - it shows this error on all avatars

**Comment by ArnavK-09** [comment]
Any fixes?

**Comment by emmatown** [comment]
This is likely caused by there being an error fetching the files for that entry, #920 adds a more specific error in that case. Could you try `@keystatic/core@0.3.10` and see if the error changes?

**Comment by ArnavK-09** [comment]
✨ Thanks to both of you it is fine now
